/** Auto-generated by scripts/sync-guide-pages.mjs — do not edit by hand. */
export type GuidePage = { id: string; title: string; body: string };

export const guidePages: GuidePage[] = [
  {
    id: "come-si-gioca",
    title: "Come si gioca",
    body: "## Cassa e utile\n\nLa **cassa** è quello che hai in banca. L’utile contabile non è liquidità: puoi essere “in utile” e restare a corto di soldi se i clienti pagano tardi.\n\n## Il loop\n\n1. Accetta commesse dal tabellone (e gestisci scorte, staff, contratti).\n2. Premi **Chiudi il mese**: entrano ed escono le scadenze (fatture, affitto, stipendi, tasse).\n3. Guarda il Δ cassa, i banner (F24, decisioni) e la posta.\n\n## Obiettivo\n\nTieni la cassa in piedi. **Dodici mesi di seguito in rosso** = fine partita. In difficoltà la banca può offrirti un prestito di salvataggio.\n\nIl **Tutorial** nel menu è l’onboarding breve (tre passi). Questa **Guida** è il riferimento da consultare quando serve.",
  },
  {
    id: "fisco-e-f24",
    title: "Fisco e F24",
    body: "## Banner F24\n\nOgni mese (dopo il primo ciclo) compare il banner per versare IVA e ritenute scadute. Pagare tiene la compliance in ordine.\n\n## Se salti il versamento\n\nScatta una sanzione una tantum e peggiora la reputazione fiscale (spread banca più alto). Restare in arretrato fa maturare **mora** ogni mese.\n\n## Cartella\n\nDopo **sei mesi** continui di tasse non pagate arriva la **cartella**. Puoi:\n\n- **Paga tutto** — chiudi se hai cassa\n- **Rateizza** — piano a rate (con maggiorazione)\n- **Ignora** — rischi pignoramento e, a lungo andare, **sconfitta fiscale**\n\n## Disclaimer\n\nModello **educativo** semplificato. Non è consulenza fiscale né software da commercialista.",
  },
  {
    id: "personale-e-capacita",
    title: "Personale e capacità",
    body: "## Assumere\n\nOgni dipendente costa in busta e genera debiti (ritenute, contributi). Più gente = più slot sul tabellone, ma anche più uscite.\n\n## Limiti tipici\n\n- **Capacità piena**: non puoi accettare altre commesse finché non liberi slot (chiudi lavori, gestisci contratti, scorte).\n- **Due contratti**: al massimo due contratti multi-mese attivi; chiudine uno prima di firmarne un altro.\n- Senza scorte o sotto pressione operativa gli slot si riducono.\n\nI messaggi “capacità piena / già 2 contratti” sono avvisi rapidi (toast), non finiscono nella posta.\n\n## Oneri di fine anno\n\nA **dicembre** può arrivare un addebito annuale sugli oneri del personale: conta la testa in organico, non solo lo stipendio del mese.",
  },
  {
    id: "finanza",
    title: "Finanza",
    body: "## Prestiti\n\nLa banca può proporti un finanziamento (Euribor + spread). Compliance fiscale bassa = condizioni peggiori. In difficoltà esiste anche il prestito di salvataggio se sei in crisi di cassa.\n\n## Tesoreria\n\nPuoi parcheggiare liquidità in **tesoreria**: rende un po’ di interessi ma non conta come cassa “comoda” per certi eventi. Se uno shock porta la cassa sotto zero, la tesoreria può coprire l’emergenza.\n\n## Scorte d’emergenza\n\nSe resti a zero scorte, puoi ordinare una fornitura d’emergenza (costo fisso didattico): utile per non bloccare il mese, ma non è gratis.\n\n## Comfort e shock\n\nCon cassa molto alta il gioco può tirare shock più spesso. Non è un bug: è tensione di mid/late game.",
  },
  {
    id: "faq",
    title: "FAQ",
    body: "## Perché non posso accettare una commessa?\n\nDi solito: capacità piena, già due contratti, scorte a zero o pressione operativa. Leggi il toast rosso/grigio: dice il motivo.\n\n## Dove finiscono gli eventi?\n\nIcona **posta** in alto: è il diario di gioco. Aprire la posta segna tutto come letto. I rifiuti di capacità non finiscono lì (solo toast).\n\n## Tutorial o Guida?\n\n- **Tutorial**: tre passi all’inizio (cassa ≠ utile, chiudi mese, F24).\n- **Guida**: questo riferimento, consultabile dal menu quando vuoi.\n\n## Ho pagato tasse ma ho ancora banner gialli?\n\nControlla cartella / rateazione / altre scadenze (IRES–IRAP a giugno/novembre). Il F24 mensile non è l’unica voce fiscale.\n\n## Salvataggi\n\nTre slot locali; con account anche cloud. Dal menu: Salvataggi.",
  }
];
